# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# CI workflow for PRs and merges to main
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: PullRequest

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - "release/stable"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build and test
        run: |
          npm i -g npm@8.19.4
          npm ci
          npm run ci
        env:
          AZ_DevOps_Read_PAT: ${{ secrets.AZ_DevOps_Read_PAT }}
