name: Create Release & Publish Npm Package

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build_publish:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: "https://npm.pkg.github.com"

      - name: Build
        run: |
          npm i
          npm run dist
        env:
          AZ_DevOps_Read_PAT: ${{ secrets.AZ_DevOps_Read_PAT }}

      - name: Publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
